version: "3"
services:
 master:
  container_name: master
  image: jenkinsci/jenkins:2.153-slim
  ports: 
   - 8080:8080
  volumes:
   - ./jenkins_home:/var/jenkins_home
  links:
   - slave01

 slave01:
  container_name: slave01
  image: jenkinsci/ssh-slave
  environment:
   - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcjb09gzcheHz0/5fLXVZ6NeBHqhlWP4VRiMZ02gn7bC6ylWhEWJUJFnQ5yvakDQc5uRv8WEJoXnS6ILjChAiEMDWu+9L30So4StmOJlF6ybud/j0kcvsgJT6VyQ0a2yKavb8PS6OBwRIozONyBLfr4QX+e3YVWEYdw9tuO6ZzdwNlLziQtx3K43VHEGF68g5JTk4KuHCLY7iFWHEaIruNL/gVX5H62mzJYsXCIROcCyQVGKuzOTV6iCa0Jje4H07hKB+eJil7AL6nDh9Mxh7+GJrtDv00bAP8vCSQ3rjzz+iFdNDJNHkTVtM24QlQaTaLcdiJX/8G2AopwrM5LNtx
